language: python

matrix:
  include:
    - python: 3.5
      dist: trusty
      sudo: false
      env:
      - TOXENV=py35
    - python: 3.6
      dist: trusty
      sudo: false
      env:
      - TOXENV=py36
    - python: 3.7
      dist: xenial
      sudo: true
      env:
      - TOXENV=py37-flake8
    - python: 3.7
      dist: xenial
      sudo: true
      env:
      - TOXENV=py37-isort
    - python: 3.7
      dist: xenial
      sudo: true
      env:
      - TOXENV=py37

install:
  - pip install tox flake8 pep8-naming isort codecov

script:
  - tox

after_success:
  - codecov -e TOXENV
